// samples/data-fabric-app/src/components/EntitiesList.tsx
import { useMemo, useState } from 'react'
import {
  ChevronDown,
  ChevronRight,
  Database,
  ListChecks,
  RefreshCw,
  Search,
  X,
} from 'lucide-react'
import { Skeleton } from '@uipath/apollo-wind/components/ui/skeleton'
import { Badge } from '@uipath/apollo-wind/components/ui/badge'
import { Alert, AlertDescription, AlertTitle } from '@uipath/apollo-wind/components/ui/alert'
import { Button } from '@uipath/apollo-wind/components/ui/button'
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from '@uipath/apollo-wind/components/ui/tooltip'
import { useEntities } from '../hooks/useEntities'
import type { EntityGetResponse } from '@uipath/uipath-typescript/entities'
import { useChoiceSets } from '../hooks/useChoiceSets'
import type { ChoiceSetListItem } from '../hooks/useChoiceSets'
import { entityTypeTooltip, isVirtualDataObject } from '../lib/entityTypes'

interface Props {
  selectedEntityId: string | null
  selectedChoiceSetId: string | null
  onSelectEntity: (entityId: string) => void
  onSelectChoiceSet: (choiceSetId: string) => void
}

/**
 * Left sidebar listing every entity and choice set in the tenant.
 *
 * Data:
 *  - `useEntities()` calls `Entities.getAll()` for the entity catalog
 *    (choice-set entries are filtered out — they live in their own list).
 *  - `useChoiceSets()` calls `ChoiceSets.getAll()` for the choice set list.
 *
 * Sections are individually collapsible (chevron toggles) so users with
 * many entities can hide them to see choice sets, and vice versa.
 *
 * Includes a search filter (case-insensitive, matches display name + system
 * name across both sections) and a unified refresh button.
 */
export function EntitiesList({
  selectedEntityId,
  selectedChoiceSetId,
  onSelectEntity,
  onSelectChoiceSet,
}: Props) {
  const { entities, loading, error, refresh } = useEntities()
  const {
    choiceSets,
    loading: choiceSetsLoading,
    error: choiceSetsError,
    refresh: refreshChoiceSets,
  } = useChoiceSets()
  const [search, setSearch] = useState('')

  const filtered = useMemo(() => {
    const needle = search.trim().toLowerCase()
    if (!needle) return entities
    return entities.filter((e) => {
      return (
        e.displayName.toLowerCase().includes(needle) ||
        e.name.toLowerCase().includes(needle)
      )
    })
  }, [entities, search])

  const filteredChoiceSets = useMemo(() => {
    const needle = search.trim().toLowerCase()
    if (!needle) return choiceSets
    return choiceSets.filter((cs) => {
      return (
        cs.displayName.toLowerCase().includes(needle) ||
        cs.name.toLowerCase().includes(needle)
      )
    })
  }, [choiceSets, search])

  const refreshAll = async () => {
    await Promise.all([refresh(), refreshChoiceSets()])
  }

  // Collapsed-state flags for each section. Defaults to open. A user with
  // 50+ entities can collapse that section to see choice sets without
  // scrolling. When the user searches, sections auto-expand temporarily so
  // search results aren't hidden behind a collapsed header.
  const [entitiesOpen, setEntitiesOpen] = useState(true)
  const [choiceSetsOpen, setChoiceSetsOpen] = useState(true)
  const showEntities = entitiesOpen || search.trim().length > 0
  const showChoiceSets = choiceSetsOpen || search.trim().length > 0

  return (
    // Fixed-layout sidebar: header + search are sticky, list scrolls.
    <aside className="w-72 border-r bg-background flex flex-col shrink-0 min-h-0">
      <div className="px-4 py-3 border-b flex items-center justify-between shrink-0">
        <h2 className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">
          Catalog
        </h2>
        <Tooltip>
          <TooltipTrigger asChild>
            <Button
              variant="ghost"
              size="icon"
              className="h-7 w-7"
              onClick={refreshAll}
              disabled={loading || choiceSetsLoading}
            >
              <RefreshCw
                className={`h-3.5 w-3.5 ${
                  loading || choiceSetsLoading ? 'animate-spin' : ''
                }`}
              />
            </Button>
          </TooltipTrigger>
          <TooltipContent side="bottom">Refresh</TooltipContent>
        </Tooltip>
      </div>

      {/* Search input. Hidden during the initial load to keep the skeleton clean.
          Using a flex row instead of an absolutely-positioned icon — keeps the
          icon and text on the exact same baseline at any zoom level. */}
      {!loading && !error && entities.length > 0 && (
        <div className="px-3 py-2 border-b shrink-0">
          <div className="flex items-center gap-2 rounded-md border border-input bg-background px-2.5 shadow-sm focus-within:ring-1 focus-within:ring-ring">
            <Search className="h-3.5 w-3.5 text-muted-foreground shrink-0" />
            <input
              type="text"
              placeholder="Search entities & choice sets…"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="flex-1 bg-transparent py-1.5 text-sm placeholder:text-muted-foreground focus:outline-none"
            />
            {search && (
              <button
                onClick={() => setSearch('')}
                aria-label="Clear search"
                className="shrink-0 text-muted-foreground hover:text-foreground"
              >
                <X className="h-3.5 w-3.5" />
              </button>
            )}
          </div>
        </div>
      )}

      {/* Scrolling list area. Two collapsible sections: Entities + Choice Sets. */}
      <div className="flex-1 overflow-y-auto">
        {/* ─── Entities section ─── */}
        <SectionHeader
          icon={<Database className="h-3.5 w-3.5" />}
          label="Entities"
          count={!loading && !error ? entities.length : undefined}
          open={showEntities}
          forcedOpen={search.trim().length > 0}
          onToggle={() => setEntitiesOpen((v) => !v)}
        />
        {showEntities && (
          <>
            {loading && (
              <div className="p-3 space-y-2">
                {[...Array(4)].map((_, i) => (
                  <div key={i} className="space-y-1.5">
                    <Skeleton className="h-4 w-2/3" />
                    <Skeleton className="h-3 w-1/3" />
                  </div>
                ))}
              </div>
            )}
            {error && !loading && (
              <div className="p-3">
                <Alert variant="destructive">
                  <AlertTitle>Couldn't load entities</AlertTitle>
                  <AlertDescription>{error}</AlertDescription>
                </Alert>
              </div>
            )}
            {!loading && !error && entities.length === 0 && (
              <EmptyState
                icon={<Database className="h-6 w-6" />}
                title="No entities yet"
                description="Define an entity in Data Service to get started."
              />
            )}
            {!loading &&
              !error &&
              entities.length > 0 &&
              filtered.length === 0 && (
                <div className="px-4 py-3 text-xs text-muted-foreground">
                  No entities match "{search}".
                </div>
              )}
            {!loading && !error && filtered.length > 0 && (
              <ul>
                {filtered.map((e) => (
                  <EntityRow
                    key={e.id}
                    entity={e}
                    selected={selectedEntityId === e.id}
                    onSelect={onSelectEntity}
                  />
                ))}
              </ul>
            )}
          </>
        )}

        {/* ─── Choice Sets section ─── */}
        <SectionHeader
          icon={<ListChecks className="h-3.5 w-3.5" />}
          label="Choice sets"
          count={
            !choiceSetsLoading && !choiceSetsError
              ? choiceSets.length
              : undefined
          }
          open={showChoiceSets}
          forcedOpen={search.trim().length > 0}
          onToggle={() => setChoiceSetsOpen((v) => !v)}
        />
        {showChoiceSets && (
          <>
            {choiceSetsLoading && (
              <div className="p-3 space-y-2">
                {[...Array(2)].map((_, i) => (
                  <div key={i} className="space-y-1.5">
                    <Skeleton className="h-4 w-2/3" />
                  </div>
                ))}
              </div>
            )}
            {choiceSetsError && !choiceSetsLoading && (
              <div className="p-3">
                <Alert variant="destructive">
                  <AlertTitle>Couldn't load choice sets</AlertTitle>
                  <AlertDescription>{choiceSetsError}</AlertDescription>
                </Alert>
              </div>
            )}
            {!choiceSetsLoading &&
              !choiceSetsError &&
              choiceSets.length === 0 && (
                <EmptyState
                  icon={<ListChecks className="h-6 w-6" />}
                  title="No choice sets"
                  description="No choice sets defined in this tenant."
                />
              )}
            {!choiceSetsLoading &&
              !choiceSetsError &&
              choiceSets.length > 0 &&
              filteredChoiceSets.length === 0 && (
                <div className="px-4 py-3 text-xs text-muted-foreground">
                  No choice sets match "{search}".
                </div>
              )}
            {!choiceSetsLoading &&
              !choiceSetsError &&
              filteredChoiceSets.length > 0 && (
                <ul>
                  {filteredChoiceSets.map((cs) => (
                    <ChoiceSetRow
                      key={cs.id}
                      choiceSet={cs}
                      selected={selectedChoiceSetId === cs.id}
                      onSelect={onSelectChoiceSet}
                    />
                  ))}
                </ul>
              )}
          </>
        )}
      </div>
    </aside>
  )
}

/**
 * Compact section header inside the sidebar.
 *
 * Acts as a toggle button when `onToggle` is provided. While the user is
 * searching (`forcedOpen=true`), the chevron is hidden and the section
 * stays open — collapsing during search would hide matching results.
 */
function SectionHeader({
  icon,
  label,
  count,
  open,
  forcedOpen,
  onToggle,
}: {
  icon: React.ReactNode
  label: string
  count?: number
  open: boolean
  forcedOpen?: boolean
  onToggle?: () => void
}) {
  const interactive = onToggle && !forcedOpen
  return (
    <button
      type="button"
      onClick={interactive ? onToggle : undefined}
      disabled={!interactive}
      className={`w-full flex items-center gap-1.5 px-4 pt-3 pb-1.5 text-xs font-semibold text-muted-foreground uppercase tracking-wide ${
        interactive
          ? 'hover:text-foreground transition-colors cursor-pointer'
          : 'cursor-default'
      }`}
      aria-expanded={open}
    >
      {interactive &&
        (open ? (
          <ChevronDown className="h-3 w-3" />
        ) : (
          <ChevronRight className="h-3 w-3" />
        ))}
      <span className="text-muted-foreground/70">{icon}</span>
      <span>{label}</span>
      {typeof count === 'number' && (
        <span className="text-muted-foreground/70">· {count}</span>
      )}
    </button>
  )
}

function ChoiceSetRow({
  choiceSet,
  selected,
  onSelect,
}: {
  choiceSet: ChoiceSetListItem
  selected: boolean
  onSelect: (id: string) => void
}) {
  return (
    <li>
      <button
        onClick={() => onSelect(choiceSet.id)}
        className={`w-full text-left px-4 py-2 text-sm border-l-2 transition-colors ${
          selected
            ? 'border-primary bg-accent text-accent-foreground font-medium'
            : 'border-transparent text-foreground hover:bg-accent/50'
        }`}
        title={choiceSet.description || choiceSet.displayName}
      >
        <div className="flex items-center justify-between gap-2">
          <span className="truncate">
            {choiceSet.displayName || choiceSet.name}
          </span>
        </div>
        {choiceSet.description && (
          <div className="text-xs text-muted-foreground mt-0.5 truncate">
            {choiceSet.description}
          </div>
        )}
      </button>
    </li>
  )
}

function EntityRow({
  entity,
  selected,
  onSelect,
}: {
  entity: EntityGetResponse
  selected: boolean
  onSelect: (id: string) => void
}) {
  const isVDO = isVirtualDataObject(entity)
  const isNonStandard = entity.entityType && entity.entityType !== 'Entity'
  const tooltipText = isVDO
    ? 'Virtual Data Object — sourced from external systems via joins'
    : entityTypeTooltip(entity.entityType)
  const badgeLabel = isVDO ? 'VDO' : entity.entityType

  return (
    <li>
      <button
        onClick={() => onSelect(entity.id)}
        className={`w-full text-left px-4 py-2 text-sm border-l-2 transition-colors ${
          selected
            ? 'border-primary bg-accent text-accent-foreground font-medium'
            : 'border-transparent text-foreground hover:bg-accent/50'
        }`}
      >
        <div className="flex items-center justify-between gap-2">
          <span className="truncate">
            {entity.displayName || entity.name}
          </span>
          {(isVDO || isNonStandard) && badgeLabel && (
            <Tooltip>
              <TooltipTrigger asChild>
                <Badge variant="secondary" className="shrink-0">
                  {badgeLabel}
                </Badge>
              </TooltipTrigger>
              <TooltipContent side="bottom" className="max-w-xs">
                {tooltipText}
              </TooltipContent>
            </Tooltip>
          )}
        </div>
        {typeof entity.recordCount === 'number' && !isVDO && (
          <div className="text-xs text-muted-foreground mt-0.5">
            {entity.recordCount} record{entity.recordCount === 1 ? '' : 's'}
          </div>
        )}
      </button>
    </li>
  )
}

function EmptyState({
  icon,
  title,
  description,
}: {
  icon: React.ReactNode
  title: string
  description: string
}) {
  return (
    <div className="p-6 text-center">
      <div className="w-10 h-10 rounded-lg bg-muted flex items-center justify-center mx-auto mb-2 text-muted-foreground">
        {icon}
      </div>
      <div className="text-sm font-medium">{title}</div>
      <div className="text-xs text-muted-foreground mt-0.5">{description}</div>
    </div>
  )
}

// samples/data-fabric-app-angular/src/app/components/entities-list.component.ts
import { Component, computed, inject, input, output, signal } from '@angular/core'
import { FormsModule } from '@angular/forms'
import { ChoiceSets, Entities } from '@uipath/uipath-typescript/entities'
import type {
  ChoiceSetGetAllResponse,
  EntityGetResponse,
} from '@uipath/uipath-typescript/entities'
import { UiPathError } from '@uipath/uipath-typescript/core'
import { AuthService } from '../core/auth.service'
import { entityTypeTooltip, isVirtualDataObject } from '../lib/entity-types'
import {
  IconChevronDown,
  IconChevronRight,
  IconDatabase,
  IconListChecks,
  IconRefresh,
  IconSearch,
  IconX,
} from './icons'

/**
 * Left sidebar listing every entity and choice set in the tenant.
 *
 * Data:
 *  - `Entities.getAll()` for the entity catalog (choice-set entries are
 *    filtered out — they live in their own list).
 *  - `ChoiceSets.getAll()` for the choice set list, which carries
 *    choice-set-specific metadata (description, updatedTime) the entity
 *    endpoint doesn't include.
 *
 * Sections are individually collapsible (chevron toggles) so users with
 * many entities can hide them to see choice sets, and vice versa.
 *
 * Includes a search filter (case-insensitive, matches display name + system
 * name across both sections) and a unified refresh button.
 */
@Component({
  selector: 'app-entities-list',
  imports: [
    FormsModule,
    IconChevronDown,
    IconChevronRight,
    IconDatabase,
    IconListChecks,
    IconRefresh,
    IconSearch,
    IconX,
  ],
  styles: `
    aside {
      width: 288px;
      border-right: 1px solid var(--border);
      background: var(--background);
      display: flex;
      flex-direction: column;
      flex-shrink: 0;
      min-height: 0;
    }
    .sidebar-header {
      padding: 12px 16px;
      border-bottom: 1px solid var(--border);
      display: flex;
      align-items: center;
      justify-content: space-between;
      flex-shrink: 0;
    }
    .sidebar-title {
      font-size: 11.5px;
      font-weight: 600;
      color: var(--muted-foreground);
      text-transform: uppercase;
      letter-spacing: 0.04em;
    }
    .search-row {
      padding: 8px 12px;
      border-bottom: 1px solid var(--border);
      flex-shrink: 0;
    }
    .search-box {
      display: flex;
      align-items: center;
      gap: 8px;
      border: 1px solid var(--input);
      border-radius: 6px;
      background: var(--background);
      padding: 0 10px;
      color: var(--muted-foreground);
    }
    .search-box:focus-within {
      border-color: var(--ring);
      box-shadow: 0 0 0 1px var(--ring);
    }
    .search-box input {
      flex: 1;
      min-width: 0;
      border: none;
      background: transparent;
      color: var(--foreground);
      padding: 6px 0;
      font-size: 13.5px;
      font-family: inherit;
    }
    .search-box input:focus { outline: none; }
    .search-clear {
      border: none;
      background: none;
      color: var(--muted-foreground);
      cursor: pointer;
      padding: 0;
      display: inline-flex;
    }
    .search-clear:hover { color: var(--foreground); }
    .sidebar-list { flex: 1; overflow-y: auto; }
    .section-header {
      width: 100%;
      display: flex;
      align-items: center;
      gap: 6px;
      padding: 12px 16px 6px;
      border: none;
      background: none;
      font-size: 11.5px;
      font-weight: 600;
      color: var(--muted-foreground);
      text-transform: uppercase;
      letter-spacing: 0.04em;
      cursor: pointer;
    }
    .section-header:hover:not(:disabled) { color: var(--foreground); }
    .section-header:disabled { cursor: default; }
    .section-count { color: color-mix(in srgb, var(--muted-foreground) 70%, transparent); }
    ul { list-style: none; margin: 0; padding: 0; }
    .row-btn {
      width: 100%;
      text-align: left;
      padding: 8px 16px;
      font-size: 13.5px;
      border: none;
      border-left: 2px solid transparent;
      background: none;
      color: var(--foreground);
      cursor: pointer;
      font-family: inherit;
    }
    .row-btn:hover { background: color-mix(in srgb, var(--accent) 50%, transparent); }
    .row-btn.selected {
      border-left-color: var(--primary);
      background: var(--accent);
      font-weight: 500;
    }
    .row-main {
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 8px;
    }
    .row-sub {
      font-size: 11.5px;
      color: var(--muted-foreground);
      margin-top: 2px;
    }
    .skeleton-block { padding: 12px; display: flex; flex-direction: column; gap: 10px; }
    .alert-wrap { padding: 12px; }
    .empty-state { padding: 24px; text-align: center; }
    .empty-icon {
      width: 40px;
      height: 40px;
      border-radius: var(--radius);
      background: var(--muted);
      color: var(--muted-foreground);
      display: flex;
      align-items: center;
      justify-content: center;
      margin: 0 auto 8px;
      font-size: 18px;
    }
    .empty-title { font-size: 13.5px; font-weight: 500; }
    .empty-description { font-size: 11.5px; color: var(--muted-foreground); margin-top: 2px; }
    .no-match { padding: 12px 16px; font-size: 12px; color: var(--muted-foreground); }
  `,
  template: `
    <aside>
      <div class="sidebar-header">
        <h2 class="sidebar-title">Catalog</h2>
        <button
          type="button"
          class="btn btn-ghost btn-icon"
          title="Refresh"
          [disabled]="loading() || choiceSetsLoading()"
          (click)="refreshAll()"
        >
          <icon-refresh [class.spin]="loading() || choiceSetsLoading()" />
        </button>
      </div>

      <!-- Search input. Hidden during the initial load to keep the skeleton clean. -->
      @if (!loading() && !error() && entities().length > 0) {
        <div class="search-row">
          <div class="search-box">
            <icon-search />
            <input
              type="text"
              placeholder="Search entities & choice sets…"
              [(ngModel)]="search"
            />
            @if (search()) {
              <button
                type="button"
                class="search-clear"
                aria-label="Clear search"
                (click)="search.set('')"
              >
                <icon-x />
              </button>
            }
          </div>
        </div>
      }

      <div class="sidebar-list">
        <!-- ─── Entities section ─── -->
        <button
          type="button"
          class="section-header"
          [disabled]="searching()"
          [attr.aria-expanded]="showEntities()"
          (click)="entitiesOpen.set(!entitiesOpen())"
        >
          @if (!searching()) {
            @if (showEntities()) {
              <icon-chevron-down />
            } @else {
              <icon-chevron-right />
            }
          }
          <icon-database />
          <span>Entities</span>
          @if (!loading() && !error()) {
            <span class="section-count">· {{ entities().length }}</span>
          }
        </button>

        @if (showEntities()) {
          @if (loading()) {
            <div class="skeleton-block">
              @for (i of [1, 2, 3, 4]; track i) {
                <div>
                  <span class="skeleton" style="height: 16px; width: 66%"></span>
                  <span class="skeleton" style="height: 12px; width: 33%; margin-top: 6px"></span>
                </div>
              }
            </div>
          } @else if (error(); as err) {
            <div class="alert-wrap">
              <div class="alert alert-destructive">
                <div class="alert-title">Couldn't load entities</div>
                <div class="alert-description">{{ err }}</div>
              </div>
            </div>
          } @else if (entities().length === 0) {
            <div class="empty-state">
              <div class="empty-icon"><icon-database /></div>
              <div class="empty-title">No entities yet</div>
              <div class="empty-description">
                Define an entity in Data Service to get started.
              </div>
            </div>
          } @else if (filteredEntities().length === 0) {
            <div class="no-match">No entities match "{{ search() }}".</div>
          } @else {
            <ul>
              @for (entity of filteredEntities(); track entity.id) {
                <li>
                  <button
                    type="button"
                    class="row-btn"
                    [class.selected]="selectedEntityId() === entity.id"
                    (click)="selectEntity.emit(entity.id)"
                  >
                    <div class="row-main">
                      <span class="truncate">
                        {{ entity.displayName || entity.name }}
                      </span>
                      @if (entityBadge(entity); as badge) {
                        <span
                          class="badge badge-secondary"
                          [title]="entityTooltip(entity)"
                        >
                          {{ badge }}
                        </span>
                      }
                    </div>
                    @if (entity.recordCount !== undefined && !isVdo(entity)) {
                      <div class="row-sub">
                        {{ entity.recordCount }}
                        record{{ entity.recordCount === 1 ? '' : 's' }}
                      </div>
                    }
                  </button>
                </li>
              }
            </ul>
          }
        }

        <!-- ─── Choice Sets section ─── -->
        <button
          type="button"
          class="section-header"
          [disabled]="searching()"
          [attr.aria-expanded]="showChoiceSets()"
          (click)="choiceSetsOpen.set(!choiceSetsOpen())"
        >
          @if (!searching()) {
            @if (showChoiceSets()) {
              <icon-chevron-down />
            } @else {
              <icon-chevron-right />
            }
          }
          <icon-list-checks />
          <span>Choice sets</span>
          @if (!choiceSetsLoading() && !choiceSetsError()) {
            <span class="section-count">· {{ choiceSets().length }}</span>
          }
        </button>

        @if (showChoiceSets()) {
          @if (choiceSetsLoading()) {
            <div class="skeleton-block">
              @for (i of [1, 2]; track i) {
                <span class="skeleton" style="height: 16px; width: 66%"></span>
              }
            </div>
          } @else if (choiceSetsError(); as err) {
            <div class="alert-wrap">
              <div class="alert alert-destructive">
                <div class="alert-title">Couldn't load choice sets</div>
                <div class="alert-description">{{ err }}</div>
              </div>
            </div>
          } @else if (choiceSets().length === 0) {
            <div class="empty-state">
              <div class="empty-icon"><icon-list-checks /></div>
              <div class="empty-title">No choice sets</div>
              <div class="empty-description">
                No choice sets defined in this tenant.
              </div>
            </div>
          } @else if (filteredChoiceSets().length === 0) {
            <div class="no-match">No choice sets match "{{ search() }}".</div>
          } @else {
            <ul>
              @for (cs of filteredChoiceSets(); track cs.id) {
                <li>
                  <button
                    type="button"
                    class="row-btn"
                    [class.selected]="selectedChoiceSetId() === cs.id"
                    [title]="cs.description || cs.displayName"
                    (click)="selectChoiceSet.emit(cs.id)"
                  >
                    <div class="row-main">
                      <span class="truncate">{{ cs.displayName || cs.name }}</span>
                    </div>
                    @if (cs.description) {
                      <div class="row-sub truncate">{{ cs.description }}</div>
                    }
                  </button>
                </li>
              }
            </ul>
          }
        }
      </div>
    </aside>
  `,
})
export class EntitiesListComponent {
  private readonly auth = inject(AuthService)

  readonly selectedEntityId = input<string | null>(null)
  readonly selectedChoiceSetId = input<string | null>(null)
  readonly selectEntity = output<string>()
  readonly selectChoiceSet = output<string>()

  readonly entities = signal<EntityGetResponse[]>([])
  readonly loading = signal(true)
  readonly error = signal<string | null>(null)

  readonly choiceSets = signal<ChoiceSetGetAllResponse[]>([])
  readonly choiceSetsLoading = signal(true)
  readonly choiceSetsError = signal<string | null>(null)

  readonly search = signal('')
  readonly searching = computed(() => this.search().trim().length > 0)

  // Collapsed-state flags for each section. Defaults to open. A user with
  // 50+ entities can collapse that section to see choice sets without
  // scrolling. When the user searches, sections auto-expand temporarily so
  // search results aren't hidden behind a collapsed header.
  readonly entitiesOpen = signal(true)
  readonly choiceSetsOpen = signal(true)
  readonly showEntities = computed(() => this.entitiesOpen() || this.searching())
  readonly showChoiceSets = computed(
    () => this.choiceSetsOpen() || this.searching(),
  )

  readonly filteredEntities = computed(() => {
    const needle = this.search().trim().toLowerCase()
    if (!needle) return this.entities()
    return this.entities().filter(
      (e) =>
        e.displayName.toLowerCase().includes(needle) ||
        e.name.toLowerCase().includes(needle),
    )
  })

  readonly filteredChoiceSets = computed(() => {
    const needle = this.search().trim().toLowerCase()
    if (!needle) return this.choiceSets()
    return this.choiceSets().filter(
      (cs) =>
        cs.displayName.toLowerCase().includes(needle) ||
        cs.name.toLowerCase().includes(needle),
    )
  })

  constructor() {
    void this.refreshAll()
  }

  async refreshAll(): Promise<void> {
    await Promise.all([this.loadEntities(), this.loadChoiceSets()])
  }

  private async loadEntities(): Promise<void> {
    this.loading.set(true)
    this.error.set(null)
    try {
      // Construct a service instance per call. The SDK keeps these cheap;
      // there's no shared client to manage. The instance is bound to the
      // authenticated `sdk` from AuthService.
      const entityService = new Entities(this.auth.sdk)
      // `Entities.getAll()` returns `EntityGetResponse[]` directly (no
      // pagination wrapper). Filter out ChoiceSet items here so they don't
      // show up in both the entities and choice-sets sidebar sections —
      // the choice-sets section is sourced from `ChoiceSets.getAll()` and
      // carries choice-set-specific metadata.
      const allEntities = await entityService.getAll()
      this.entities.set(allEntities.filter((e) => e.entityType !== 'ChoiceSet'))
    } catch (err) {
      this.error.set(
        err instanceof UiPathError ? err.message : 'Failed to load entities',
      )
    } finally {
      this.loading.set(false)
    }
  }

  private async loadChoiceSets(): Promise<void> {
    this.choiceSetsLoading.set(true)
    this.choiceSetsError.set(null)
    try {
      const choiceSetService = new ChoiceSets(this.auth.sdk)
      // `ChoiceSets.getAll()` returns `ChoiceSetGetAllResponse[]` directly.
      this.choiceSets.set(await choiceSetService.getAll())
    } catch (err) {
      this.choiceSetsError.set(
        err instanceof UiPathError ? err.message : 'Failed to load choice sets',
      )
    } finally {
      this.choiceSetsLoading.set(false)
    }
  }

  isVdo(entity: EntityGetResponse): boolean {
    return isVirtualDataObject(entity)
  }

  /** Badge label for non-standard entities (VDO / SystemEntity / …). */
  entityBadge(entity: EntityGetResponse): string | null {
    if (isVirtualDataObject(entity)) return 'VDO'
    if (entity.entityType && entity.entityType !== 'Entity') {
      return entity.entityType
    }
    return null
  }

  entityTooltip(entity: EntityGetResponse): string {
    return isVirtualDataObject(entity)
      ? 'Virtual Data Object — sourced from external systems via joins'
      : entityTypeTooltip(entity.entityType)
  }
}
