// samples/data-fabric-app/src/components/Header.tsx
import { Database, LogOut } from 'lucide-react'
import { useAuth } from '../hooks/useAuth'
import { Button } from '@/components/ui/button'
import { ThemeToggle } from './ThemeToggle'

export function Header() {
  const { logout } = useAuth()
  return (
    <header className="border-b bg-background shrink-0">
      {/* Full-width header — no max-width clamp, so the title hugs the
          left edge and the controls hug the right edge regardless of
          viewport size. */}
      <div className="px-4 sm:px-6 lg:px-8 py-3 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="w-7 h-7 rounded-md bg-primary/10 flex items-center justify-center">
            <Database className="h-4 w-4 text-primary" />
          </div>
          <h1 className="text-base font-semibold">Data Fabric Explorer</h1>
        </div>
        <div className="flex items-center gap-1">
          <ThemeToggle />
          <Button variant="ghost" size="sm" onClick={logout}>
            <LogOut className="h-4 w-4 mr-1.5" />
            Sign out
          </Button>
        </div>
      </div>
    </header>
  )
}

// samples/data-fabric-app-angular/src/app/components/header.component.ts
import { Component, inject } from '@angular/core'
import { AuthService } from '../core/auth.service'
import { ThemeService } from '../core/theme.service'
import { IconDatabase, IconLogOut, IconMoon, IconSun } from './icons'

@Component({
  selector: 'app-header',
  imports: [IconDatabase, IconLogOut, IconMoon, IconSun],
  styles: `
    header {
      border-bottom: 1px solid var(--border);
      background: var(--background);
      flex-shrink: 0;
    }
    .header-inner {
      padding: 10px 24px;
      display: flex;
      align-items: center;
      justify-content: space-between;
    }
    .header-brand { display: flex; align-items: center; gap: 8px; }
    .header-logo {
      width: 28px;
      height: 28px;
      border-radius: 6px;
      background: color-mix(in srgb, var(--primary) 10%, transparent);
      color: var(--primary);
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 15px;
    }
    .header-title { font-size: 15px; font-weight: 600; }
    .header-actions { display: flex; align-items: center; gap: 4px; }
  `,
  template: `
    <header>
      <div class="header-inner">
        <div class="header-brand">
          <div class="header-logo"><icon-database /></div>
          <h1 class="header-title">Data Fabric Explorer</h1>
        </div>
        <div class="header-actions">
          <button
            type="button"
            class="btn btn-ghost btn-icon"
            [title]="theme.theme() === 'dark' ? 'Switch to light mode' : 'Switch to dark mode'"
            (click)="theme.toggle()"
          >
            @if (theme.theme() === 'dark') {
              <icon-sun />
            } @else {
              <icon-moon />
            }
          </button>
          <button type="button" class="btn btn-ghost btn-sm" (click)="auth.logout()">
            <icon-log-out />
            Sign out
          </button>
        </div>
      </div>
    </header>
  `,
})
export class HeaderComponent {
  readonly auth = inject(AuthService)
  readonly theme = inject(ThemeService)
}
