// samples/data-fabric-app/src/components/RowInspector.tsx
import { useEffect, useState } from 'react'
import { toast } from 'sonner'
import { Download } from 'lucide-react'
import { Entities } from '@uipath/uipath-typescript/entities'
import { UiPathError } from '@uipath/uipath-typescript/core'
import { useAuth } from '../hooks/useAuth'
import type { EntitySchema, EntityRow } from '../hooks/useEntity'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Skeleton } from '@/components/ui/skeleton'
import { downloadBlobAsFile } from '../lib/download'

interface Props {
  entityId: string
  recordId: string
  schema: EntitySchema
  onClose: () => void
}

/**
 * Read-only "inspect" panel for a single record.
 *
 * SDK calls used:
 *  - `Entities.getRecordById(entityId, recordId)` to load the full record
 *    (the widget filters out system fields like CreatedTime / UpdatedBy /
 *    CreatedBy / UpdatedTime; this view re-exposes them).
 *  - `Entities.downloadAttachment(entityId, recordId, fieldName)` for any
 *    File-type field that has an attachment.
 */
export function RowInspector({ entityId, recordId, schema, onClose }: Props) {
  const { sdk } = useAuth()
  const [record, setRecord] = useState<EntityRow | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [downloadingField, setDownloadingField] = useState<string | null>(null)

  useEffect(() => {
    let cancelled = false
    const load = async () => {
      setLoading(true)
      setError(null)
      try {
        const svc = new Entities(sdk)
        const r = (await svc.getRecordById(entityId, recordId)) as EntityRow
        if (!cancelled) setRecord(r)
      } catch (err) {
        if (!cancelled) {
          setError(
            err instanceof UiPathError ? err.message : 'Failed to load record',
          )
        }
      } finally {
        if (!cancelled) setLoading(false)
      }
    }
    load()
    return () => {
      cancelled = true
    }
  }, [sdk, entityId, recordId])

  const handleDownload = async (fieldName: string) => {
    setDownloadingField(fieldName)
    try {
      const svc = new Entities(sdk)
      const blob = await svc.downloadAttachment(entityId, recordId, fieldName)
      // Use the field name as filename. The blob has a `type` so the browser
      // will pick a sensible default extension, but we can't recover the
      // original filename without it being stored elsewhere.
      const ext = blobExtension(blob)
      downloadBlobAsFile(blob, `${fieldName}${ext}`)
      toast.success(`Downloaded ${fieldName}`)
    } catch (err) {
      toast.error('Download failed', {
        description:
          err instanceof UiPathError ? err.message : 'Unknown error',
      })
    } finally {
      setDownloadingField(null)
    }
  }

  return (
    <Dialog open onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="sm:max-w-2xl">
        <DialogHeader>
          <DialogTitle>Record details</DialogTitle>
          <DialogDescription>
            All fields including system metadata.{' '}
            <code className="font-mono text-xs">{recordId}</code>
          </DialogDescription>
        </DialogHeader>

        <div className="max-h-[60vh] overflow-y-auto pr-1">
          {loading && (
            <div className="space-y-2">
              {[...Array(6)].map((_, i) => (
                <div key={i} className="grid grid-cols-3 gap-3 py-1">
                  <Skeleton className="h-4 col-span-1" />
                  <Skeleton className="h-4 col-span-2" />
                </div>
              ))}
            </div>
          )}

          {error && (
            <Alert variant="destructive">
              <AlertTitle>Couldn't load this record</AlertTitle>
              <AlertDescription>{error}</AlertDescription>
            </Alert>
          )}

          {!loading && !error && record && (
            <table className="w-full text-sm">
              <tbody>
                {schema.fields.map((f) => {
                  const value = record[f.name]
                  return (
                    <tr key={f.id} className="border-b last:border-b-0">
                      <td className="py-2 pr-4 align-top text-muted-foreground font-medium w-1/3">
                        {f.displayName || f.name}
                        {f.isSystemField && (
                          <span className="ml-1.5 text-[10px] uppercase tracking-wide text-muted-foreground/70">
                            system
                          </span>
                        )}
                      </td>
                      <td className="py-2 align-top break-words">
                        {f.isAttachment ? (
                          value ? (
                            <Button
                              size="sm"
                              variant="outline"
                              disabled={downloadingField === f.name}
                              onClick={() => handleDownload(f.name)}
                            >
                              <Download className="h-3.5 w-3.5 mr-1.5" />
                              {downloadingField === f.name
                                ? 'Downloading…'
                                : 'Download'}
                            </Button>
                          ) : (
                            <span className="text-muted-foreground italic">
                              no attachment
                            </span>
                          )
                        ) : (
                          <FieldValue value={value} />
                        )}
                      </td>
                    </tr>
                  )
                })}
              </tbody>
            </table>
          )}
        </div>

        <DialogFooter>
          <Button onClick={onClose}>Close</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}

function FieldValue({ value }: { value: unknown }) {
  if (value === null || value === undefined || value === '') {
    return <span className="text-muted-foreground italic">empty</span>
  }
  if (typeof value === 'object') {
    return (
      <pre className="text-xs bg-muted p-2 rounded overflow-x-auto">
        {JSON.stringify(value, null, 2)}
      </pre>
    )
  }
  return <span className="font-mono text-xs">{String(value)}</span>
}

/** Crude file-extension guess from a Blob's MIME type. */
function blobExtension(blob: Blob): string {
  const type = blob.type
  if (!type) return ''
  if (type.includes('pdf')) return '.pdf'
  if (type.includes('png')) return '.png'
  if (type.includes('jpeg') || type.includes('jpg')) return '.jpg'
  if (type.includes('csv')) return '.csv'
  if (type.includes('json')) return '.json'
  if (type.includes('xml')) return '.xml'
  if (type.includes('text/plain')) return '.txt'
  return ''
}

// samples/data-fabric-app-angular/src/app/components/row-inspector.component.ts
import { Component, inject, input, output, signal } from '@angular/core'
import type { OnInit } from '@angular/core'
import { Entities } from '@uipath/uipath-typescript/entities'
import type { EntityGetResponse, EntityRecord } from '@uipath/uipath-typescript/entities'
import { UiPathError } from '@uipath/uipath-typescript/core'
import { AuthService } from '../core/auth.service'
import { ToastService } from '../core/toast.service'
import { downloadBlobAsFile } from '../lib/download'
import { IconDownload, IconX } from './icons'

/**
 * Read-only "inspect" panel for a single record.
 *
 * SDK calls used:
 *  - `Entities.getRecordById(entityId, recordId)` to load the full record —
 *    including system fields like CreatedTime / UpdatedBy the main grid
 *    doesn't emphasise.
 *  - `Entities.downloadAttachment(entityId, recordId, fieldName)` for any
 *    File-type field that has an attachment.
 */
@Component({
  selector: 'app-row-inspector',
  imports: [IconDownload, IconX],
  styles: `
    .dialog { max-width: 680px; position: relative; }
    .dialog-close {
      position: absolute;
      top: 14px;
      right: 14px;
      border: none;
      background: none;
      color: var(--muted-foreground);
      cursor: pointer;
      padding: 4px;
      display: inline-flex;
    }
    .dialog-close:hover { color: var(--foreground); }
    .record-table { width: 100%; border-collapse: collapse; font-size: 13.5px; }
    .record-table td {
      padding: 8px 0;
      border-bottom: 1px solid var(--border);
      vertical-align: top;
    }
    .record-table tr:last-child td { border-bottom: none; }
    .field-name {
      color: var(--muted-foreground);
      font-weight: 500;
      width: 33%;
      padding-right: 16px !important;
    }
    .system-tag {
      margin-left: 6px;
      font-size: 10px;
      text-transform: uppercase;
      letter-spacing: 0.04em;
      color: color-mix(in srgb, var(--muted-foreground) 70%, transparent);
    }
    .field-value { word-break: break-word; }
    .value-mono { font-family: var(--font-mono); font-size: 12px; }
    .value-empty { color: var(--muted-foreground); font-style: italic; }
    .value-object {
      font-size: 12px;
      background: var(--muted);
      padding: 8px;
      border-radius: 6px;
      overflow-x: auto;
      margin: 0;
    }
    .skeleton-rows { display: flex; flex-direction: column; gap: 10px; }
    .skeleton-row { display: flex; gap: 12px; }
  `,
  template: `
    <div class="dialog-backdrop" (click)="onBackdropClick($event)">
      <div class="dialog" role="dialog" aria-modal="true">
        <button type="button" class="dialog-close" aria-label="Close" (click)="closed.emit()">
          <icon-x />
        </button>
        <div>
          <h2 class="dialog-title">Record details</h2>
          <p class="dialog-description">
            All fields including system metadata.
            <code style="font-size: 11.5px">{{ recordId() }}</code>
          </p>
        </div>

        <div class="dialog-body">
          @if (loading()) {
            <div class="skeleton-rows">
              @for (i of [1, 2, 3, 4, 5, 6]; track i) {
                <div class="skeleton-row">
                  <span class="skeleton" style="height: 16px; width: 33%"></span>
                  <span class="skeleton" style="height: 16px; flex: 1"></span>
                </div>
              }
            </div>
          } @else if (error(); as err) {
            <div class="alert alert-destructive">
              <div class="alert-title">Couldn't load this record</div>
              <div class="alert-description">{{ err }}</div>
            </div>
          } @else if (record(); as rec) {
            <table class="record-table">
              <tbody>
                @for (field of schema().fields; track field.id) {
                  <tr>
                    <td class="field-name">
                      {{ field.displayName || field.name }}
                      @if (field.isSystemField) {
                        <span class="system-tag">system</span>
                      }
                    </td>
                    <td class="field-value">
                      @if (field.isAttachment) {
                        @if (rec[field.name]) {
                          <button
                            type="button"
                            class="btn btn-outline btn-sm"
                            [disabled]="downloadingField() === field.name"
                            (click)="download(field.name)"
                          >
                            <icon-download />
                            {{
                              downloadingField() === field.name
                                ? 'Downloading…'
                                : 'Download'
                            }}
                          </button>
                        } @else {
                          <span class="value-empty">no attachment</span>
                        }
                      } @else if (isEmpty(rec[field.name])) {
                        <span class="value-empty">empty</span>
                      } @else if (isObject(rec[field.name])) {
                        <pre class="value-object">{{ pretty(rec[field.name]) }}</pre>
                      } @else {
                        <span class="value-mono">{{ rec[field.name] }}</span>
                      }
                    </td>
                  </tr>
                }
              </tbody>
            </table>
          }
        </div>

        <div class="dialog-footer">
          <button type="button" class="btn btn-primary" (click)="closed.emit()">
            Close
          </button>
        </div>
      </div>
    </div>
  `,
})
export class RowInspectorComponent implements OnInit {
  private readonly auth = inject(AuthService)
  private readonly toast = inject(ToastService)

  readonly entityId = input.required<string>()
  readonly recordId = input.required<string>()
  readonly schema = input.required<EntityGetResponse>()
  readonly closed = output<void>()

  readonly record = signal<EntityRecord | null>(null)
  readonly loading = signal(true)
  readonly error = signal<string | null>(null)
  readonly downloadingField = signal<string | null>(null)

  ngOnInit(): void {
    void this.load()
  }

  private async load(): Promise<void> {
    this.loading.set(true)
    this.error.set(null)
    try {
      const entityService = new Entities(this.auth.sdk)
      const record = await entityService.getRecordById(
        this.entityId(),
        this.recordId(),
      )
      this.record.set(record as EntityRecord)
    } catch (err) {
      this.error.set(
        err instanceof UiPathError ? err.message : 'Failed to load record',
      )
    } finally {
      this.loading.set(false)
    }
  }

  async download(fieldName: string): Promise<void> {
    this.downloadingField.set(fieldName)
    try {
      const entityService = new Entities(this.auth.sdk)
      const blob = await entityService.downloadAttachment(
        this.entityId(),
        this.recordId(),
        fieldName,
      )
      // Use the field name as filename. The blob has a `type` so the browser
      // will pick a sensible default extension, but we can't recover the
      // original filename without it being stored elsewhere.
      downloadBlobAsFile(blob, `${fieldName}${blobExtension(blob)}`)
      this.toast.success(`Downloaded ${fieldName}`)
    } catch (err) {
      this.toast.error(
        'Download failed',
        err instanceof UiPathError ? err.message : 'Unknown error',
      )
    } finally {
      this.downloadingField.set(null)
    }
  }

  onBackdropClick(event: MouseEvent): void {
    if (event.target === event.currentTarget) this.closed.emit()
  }

  isEmpty(value: unknown): boolean {
    return value === null || value === undefined || value === ''
  }

  isObject(value: unknown): boolean {
    return typeof value === 'object' && value !== null
  }

  pretty(value: unknown): string {
    return JSON.stringify(value, null, 2)
  }
}

/** Crude file-extension guess from a Blob's MIME type. */
function blobExtension(blob: Blob): string {
  const type = blob.type
  if (!type) return ''
  if (type.includes('pdf')) return '.pdf'
  if (type.includes('png')) return '.png'
  if (type.includes('jpeg') || type.includes('jpg')) return '.jpg'
  if (type.includes('csv')) return '.csv'
  if (type.includes('json')) return '.json'
  if (type.includes('xml')) return '.xml'
  if (type.includes('text/plain')) return '.txt'
  return ''
}
