// samples/data-fabric-app-angular/src/app/components/choice-set-detail.component.ts
import { Component, effect, inject, input, signal, untracked } from '@angular/core'
import { ChoiceSets } from '@uipath/uipath-typescript/entities'
import type { ChoiceSetGetAllResponse } from '@uipath/uipath-typescript/entities'
import { AuthService } from '../core/auth.service'
import { ChoiceSetViewComponent } from './choice-set-view.component'
import { IconListChecks } from './icons'

/**
 * Right-pane detail view for one ChoiceSet.
 *
 * ChoiceSets aren't entities — they have a separate SDK service, so we
 * can't reuse `EntityDetailComponent` here (`Entities.getById()` returns a
 * sparse object on choice-set IDs, with no `fields` array).
 *
 * Composition:
 *  - Header: pulls metadata (display name, description, updatedTime) from
 *    `ChoiceSets.getAll()`.
 *  - Body: `<app-choice-set-view>` renders the list of values via
 *    `ChoiceSets.getById()`.
 */
@Component({
  selector: 'app-choice-set-detail',
  imports: [ChoiceSetViewComponent, IconListChecks],
  styles: `
    :host { flex: 1; min-width: 0; overflow-y: auto; display: block; }
    .detail { padding: 24px; }
    .detail-header { margin-bottom: 24px; min-width: 0; }
    .title-row { display: flex; align-items: center; gap: 8px; margin-bottom: 4px; }
    .title-icon { color: var(--muted-foreground); font-size: 18px; }
    .title { font-size: 19px; font-weight: 600; }
    .description { font-size: 13.5px; color: var(--muted-foreground); margin-top: 4px; }
    .meta {
      display: flex;
      flex-wrap: wrap;
      gap: 4px 16px;
      margin-top: 8px;
      font-size: 12px;
      color: var(--muted-foreground);
    }
  `,
  template: `
    <div class="detail">
      <div class="detail-header">
        <div class="title-row">
          <span class="title-icon"><icon-list-checks /></span>
          @if (loading() && !metadata()) {
            <span class="skeleton" style="height: 26px; width: 190px"></span>
          } @else {
            <h2 class="title truncate">
              {{ metadata()?.displayName || metadata()?.name || 'Choice set' }}
            </h2>
          }
          <span class="badge badge-secondary">Choice set</span>
        </div>
        @if (metadata()?.description) {
          <p class="description">{{ metadata()!.description }}</p>
        }
        @if (metadata(); as meta) {
          <div class="meta">
            @if (meta.name) {
              <span>
                System name:
                <code style="font-size: 11.5px; color: var(--foreground)">{{
                  meta.name
                }}</code>
              </span>
            }
            @if (meta.updatedTime) {
              <span>Last updated {{ formatDate(meta.updatedTime) }}</span>
            }
          </div>
        }
      </div>

      <app-choice-set-view [choiceSetId]="choiceSetId()" />
    </div>
  `,
})
export class ChoiceSetDetailComponent {
  private readonly auth = inject(AuthService)

  readonly choiceSetId = input.required<string>()

  readonly metadata = signal<ChoiceSetGetAllResponse | null>(null)
  readonly loading = signal(true)

  constructor() {
    effect(() => {
      const id = this.choiceSetId()
      untracked(() => void this.loadMetadata(id))
    })
  }

  /**
   * `ChoiceSets.getById()` returns the values, not the choice set's own
   * metadata — so the header re-fetches `getAll()` and picks this one out.
   * (Already fetched at the sidebar level, but a small refetch here keeps
   * the components decoupled and is cheap.)
   */
  private async loadMetadata(id: string): Promise<void> {
    this.loading.set(true)
    this.metadata.set(null)
    try {
      const choiceSetService = new ChoiceSets(this.auth.sdk)
      const all = await choiceSetService.getAll()
      this.metadata.set(all.find((cs) => cs.id === id) ?? null)
    } catch (err) {
      // Header metadata is decorative — the values table below surfaces
      // its own errors, so just log here.
      console.error('Failed to load choice set metadata:', err)
    } finally {
      this.loading.set(false)
    }
  }

  formatDate(value: string): string {
    return new Date(value).toLocaleString()
  }
}

// samples/data-fabric-app/src/components/ChoiceSetDetail.tsx
import { useMemo } from 'react'
import { ListChecks } from 'lucide-react'
import { Badge } from '@uipath/apollo-wind/components/ui/badge'
import { Skeleton } from '@uipath/apollo-wind/components/ui/skeleton'
import { useChoiceSets } from '../hooks/useChoiceSets'
import { ChoiceSetView } from './ChoiceSetView'

interface Props {
  choiceSetId: string
}

/**
 * Right-pane detail view for one ChoiceSet.
 *
 * ChoiceSets aren't entities — they have a separate SDK service
 * (`ChoiceSetServiceModel`), so we can't reuse `EntityDetail` here.
 * `Entities.getById()` returns a sparse object on choice-set IDs (no
 * `fields` array), which crashes the entity column-config builder.
 *
 * Composition:
 *  - Header: pulls metadata (display name, description, createdBy,
 *    updatedTime) from `ChoiceSets.getAll()` — already cached at the
 *    sidebar level, but a small refetch here is cheap.
 *  - Body: `<ChoiceSetView>` renders the list of values via
 *    `ChoiceSets.getById()`.
 *
 * The two ChoiceSet SDK methods are the full surface, and both run here
 * (one for the header metadata, one for the values).
 */
export function ChoiceSetDetail({ choiceSetId }: Props) {
  const { choiceSets, loading } = useChoiceSets()
  const metadata = useMemo(
    () => choiceSets.find((cs) => cs.id === choiceSetId),
    [choiceSets, choiceSetId],
  )

  return (
    <div className="flex-1 overflow-y-auto">
      <div className="p-6">
        <div className="flex items-start justify-between gap-4 mb-6">
          <div className="min-w-0 flex-1">
            <div className="flex items-center gap-2 mb-1">
              <ListChecks className="h-5 w-5 text-muted-foreground shrink-0" />
              {loading && !metadata ? (
                <Skeleton className="h-7 w-48" />
              ) : (
                <h2 className="text-xl font-semibold truncate">
                  {metadata?.displayName || metadata?.name || 'Choice set'}
                </h2>
              )}
              <Badge variant="secondary">Choice set</Badge>
            </div>
            {metadata?.description && (
              <p className="text-sm text-muted-foreground mt-1">
                {metadata.description}
              </p>
            )}
            {metadata && (
              <div className="flex flex-wrap items-center gap-x-4 gap-y-1 mt-2 text-xs text-muted-foreground">
                {metadata.name && (
                  <span>
                    System name:{' '}
                    <code className="font-mono text-foreground/70">
                      {metadata.name}
                    </code>
                  </span>
                )}
                {metadata.updatedTime && (
                  <span>
                    Last updated{' '}
                    {new Date(metadata.updatedTime).toLocaleString()}
                  </span>
                )}
              </div>
            )}
          </div>
        </div>

        <ChoiceSetView choiceSetId={choiceSetId} />
      </div>
    </div>
  )
}
