// samples/data-fabric-app-angular/src/app/components/entity-detail.component.ts
import { Component, computed, effect, inject, input, signal, untracked } from '@angular/core'
import { Entities } from '@uipath/uipath-typescript/entities'
import type { EntityGetResponse, EntityRecord } from '@uipath/uipath-typescript/entities'
import { UiPathError } from '@uipath/uipath-typescript/core'
import { AuthService } from '../core/auth.service'
import { ToastService } from '../core/toast.service'
import {
  entityNotSupportedReason,
  entityTypeTooltip,
  isReadOnlyEntity,
  isVirtualDataObject,
} from '../lib/entity-types'
import { exportRecordsAsCsv } from '../lib/csv-export'
import { RecordsTableComponent } from './records-table.component'
import { RecordEditorComponent } from './record-editor.component'
import { RowInspectorComponent } from './row-inspector.component'
import { ChoiceSetViewComponent } from './choice-set-view.component'
import { IconDownload, IconPlus, IconRefresh, IconTrash } from './icons'

/**
 * Right-pane detail view for one entity.
 *
 * Rendering branches by entity kind:
 *  - **Regular Entity** → full CRUD UI: records grid with sorting +
 *    pagination, Add data modal, per-row Edit modal, batch delete via row
 *    selection, CSV export, Row Inspector.
 *  - **ChoiceSet** → dedicated read-only viewer via the ChoiceSets service.
 *  - **VDO / InternalEntity** → friendly "not viewable" notice.
 *  - **SystemEntity** → records grid in read-only mode (no edit/add/delete).
 *
 * SDK calls: `Entities.getById` (schema), `Entities.getAllRecords`
 * (cursor-looped to fetch every page), `Entities.deleteRecordsById`
 * (batch delete of the selected rows). Insert/update/attachments live in
 * `RecordEditorComponent`; `getRecordById` + `downloadAttachment` live in
 * `RowInspectorComponent`.
 */
@Component({
  selector: 'app-entity-detail',
  imports: [
    RecordsTableComponent,
    RecordEditorComponent,
    RowInspectorComponent,
    ChoiceSetViewComponent,
    IconDownload,
    IconPlus,
    IconRefresh,
    IconTrash,
  ],
  styles: `
    :host { flex: 1; min-width: 0; overflow-y: auto; display: block; }
    .detail { padding: 24px; display: flex; flex-direction: column; min-height: 100%; }
    .detail-top {
      display: flex;
      align-items: flex-start;
      justify-content: space-between;
      gap: 16px;
      margin-bottom: 24px;
    }
    .detail-heading { min-width: 0; }
    .title-row { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; }
    .title { font-size: 22px; font-weight: 600; }
    .description { font-size: 13.5px; color: var(--muted-foreground); margin-top: 4px; }
    .meta { font-size: 12px; color: var(--muted-foreground); margin-top: 8px; }
    .actions { display: flex; align-items: center; gap: 8px; flex-shrink: 0; flex-wrap: wrap; }
    details.schema {
      margin-bottom: 24px;
      border: 1px solid var(--border);
      border-radius: var(--radius);
      background: var(--card);
    }
    details.schema summary {
      cursor: pointer;
      padding: 8px 16px;
      font-size: 13.5px;
      font-weight: 500;
    }
    .schema-body {
      border-top: 1px solid var(--border);
      padding: 8px 16px;
      overflow-x: auto;
    }
    .schema-table { width: 100%; border-collapse: collapse; font-size: 12.5px; }
    .schema-table th {
      text-align: left;
      padding: 4px 16px 4px 0;
      font-size: 11.5px;
      font-weight: 500;
      color: var(--muted-foreground);
    }
    .schema-table td { padding: 4px 16px 4px 0; border-top: 1px solid var(--border); }
    .records-area { flex: 1; min-height: 0; display: flex; flex-direction: column; }
    .records-area app-records-table { flex: 1; min-height: 0; display: flex; flex-direction: column; }
    .skeleton-header { margin-bottom: 24px; display: flex; flex-direction: column; gap: 8px; }
  `,
  template: `
    @if (error(); as err) {
      <div class="detail">
        <div class="alert alert-destructive">
          <div class="alert-title">Couldn't load this entity</div>
          <div class="alert-description">{{ err }}</div>
        </div>
      </div>
    } @else if (loading() || !schema()) {
      <!-- Skeleton layout matching the loaded state so the page doesn't jump. -->
      <div class="detail">
        <div class="skeleton-header">
          <span class="skeleton" style="height: 32px; width: 33%"></span>
          <span class="skeleton" style="height: 16px; width: 50%"></span>
          <span class="skeleton" style="height: 12px; width: 160px"></span>
        </div>
        <span class="skeleton" style="height: 40px; width: 100%; margin-bottom: 24px"></span>
        <span class="skeleton" style="flex: 1; min-height: 460px; width: 100%"></span>
      </div>
    } @else {
      <div class="detail">
        <div class="detail-top">
          <div class="detail-heading">
            <div class="title-row">
              <h2 class="title truncate">
                {{ schema()!.displayName || schema()!.name }}
              </h2>
              @if (badgeLabel(); as badge) {
                <span class="badge badge-secondary" [title]="badgeTooltip()">
                  {{ badge }}
                </span>
              }
              @if (readOnly()) {
                <span
                  class="badge badge-outline"
                  title="This entity is managed by the platform — records can be viewed but not edited, added, or deleted."
                >
                  Read-only
                </span>
              }
            </div>
            @if (schema()!.description) {
              <p class="description">{{ schema()!.description }}</p>
            }
            <p class="meta">
              <span class="mono">{{ schema()!.name }}</span>
              · {{ schema()!.fields.length }}
              field{{ schema()!.fields.length === 1 ? '' : 's' }}
            </p>
          </div>

          @if (!unsupportedReason() && schema()!.entityType !== 'ChoiceSet') {
            <div class="actions">
              @if (!readOnly() && selectedIds().length > 0) {
                <button
                  type="button"
                  class="btn btn-destructive"
                  [disabled]="deleting()"
                  (click)="deleteSelected()"
                >
                  <icon-trash />
                  {{
                    deleting()
                      ? 'Deleting…'
                      : 'Delete (' + selectedIds().length + ')'
                  }}
                </button>
              }
              <button
                type="button"
                class="btn btn-outline"
                title="Export records to CSV"
                [disabled]="exporting()"
                (click)="exportCsv()"
              >
                <icon-download />
                {{ exporting() ? 'Exporting…' : 'Export CSV' }}
              </button>
              <button
                type="button"
                class="btn btn-outline"
                [disabled]="recordsLoading()"
                (click)="loadRecords()"
              >
                <icon-refresh [class.spin]="recordsLoading()" />
                Refresh
              </button>
              <!-- "Add data" is hidden for read-only entities (e.g.
                   SystemEntity) — the records are queryable but not mutable. -->
              @if (!readOnly()) {
                <button type="button" class="btn btn-primary" (click)="creating.set(true)">
                  <icon-plus />
                  Add data
                </button>
              }
            </div>
          }
        </div>

        <!-- Schema (collapsible) -->
        <details class="schema">
          <summary>Schema ({{ schema()!.fields.length }} fields)</summary>
          <div class="schema-body">
            <table class="schema-table">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Type</th>
                  <th>Required</th>
                  <th>System</th>
                </tr>
              </thead>
              <tbody>
                @for (field of schema()!.fields; track field.id) {
                  <tr>
                    <td class="mono" style="font-size: 12px">{{ field.name }}</td>
                    <td>{{ field.fieldDataType.name || '—' }}</td>
                    <td>{{ field.isRequired ? 'yes' : 'no' }}</td>
                    <td>{{ field.isSystemField ? 'yes' : 'no' }}</td>
                  </tr>
                }
              </tbody>
            </table>
          </div>
        </details>

        <!-- Content varies by entity kind -->
        @if (schema()!.entityType === 'ChoiceSet') {
          <app-choice-set-view [choiceSetId]="entityId()" />
        } @else if (unsupportedReason(); as reason) {
          <div class="alert">
            <div class="alert-title">Records aren't viewable here</div>
            <div class="alert-description">{{ reason }}</div>
          </div>
        } @else {
          <div class="records-area">
            <app-records-table
              [fields]="schema()!.fields"
              [records]="records()"
              [loading]="recordsLoading()"
              [error]="recordsError()"
              [readOnly]="readOnly()"
              (inspect)="inspectingId.set($event)"
              (edit)="editingRecord.set($event)"
              (selectionChange)="selectedIds.set($event)"
            />
          </div>
        }
      </div>

      @if (creating()) {
        <app-record-editor
          [entityId]="entityId()"
          [entityDisplayName]="schema()!.displayName || schema()!.name"
          [fields]="editableFields()"
          (closed)="creating.set(false)"
          (saved)="onEditorSaved('created')"
        />
      }

      @if (editingRecord(); as record) {
        <app-record-editor
          [entityId]="entityId()"
          [entityDisplayName]="schema()!.displayName || schema()!.name"
          [fields]="editableFields()"
          [record]="record"
          (closed)="editingRecord.set(null)"
          (saved)="onEditorSaved('updated')"
        />
      }

      @if (inspectingId(); as recordId) {
        <app-row-inspector
          [entityId]="entityId()"
          [recordId]="recordId"
          [schema]="schema()!"
          (closed)="inspectingId.set(null)"
        />
      }
    }
  `,
})
export class EntityDetailComponent {
  private readonly auth = inject(AuthService)
  private readonly toast = inject(ToastService)

  readonly entityId = input.required<string>()

  readonly schema = signal<EntityGetResponse | null>(null)
  readonly loading = signal(false)
  readonly error = signal<string | null>(null)

  readonly records = signal<EntityRecord[]>([])
  readonly recordsLoading = signal(false)
  readonly recordsError = signal<string | null>(null)

  readonly exporting = signal(false)
  readonly deleting = signal(false)

  // `creating` opens the Add data modal, `editingRecord` the same modal in
  // edit mode, `inspectingId` the read-only Row Inspector (trigger: click
  // the Id cell in the records table).
  readonly creating = signal(false)
  readonly editingRecord = signal<EntityRecord | null>(null)
  readonly inspectingId = signal<string | null>(null)
  readonly selectedIds = signal<string[]>([])

  readonly unsupportedReason = computed(() => {
    const schema = this.schema()
    return schema ? entityNotSupportedReason(schema) : null
  })

  readonly readOnly = computed(() => {
    const schema = this.schema()
    return !!schema && isReadOnlyEntity(schema)
  })

  readonly badgeLabel = computed(() => {
    const schema = this.schema()
    if (!schema) return null
    if (isVirtualDataObject(schema)) return 'VDO'
    if (schema.entityType && schema.entityType !== 'Entity') {
      return schema.entityType
    }
    return null
  })

  readonly badgeTooltip = computed(() => {
    const schema = this.schema()
    if (!schema) return ''
    return isVirtualDataObject(schema)
      ? 'Virtual Data Object — sourced from external systems via joins'
      : entityTypeTooltip(schema.entityType)
  })

  /**
   * Editable fields for the modal form — drop system fields only.
   * Attachment (File-type) fields are kept; the RecordEditor handles them
   * with a file picker + upload/delete buttons.
   */
  readonly editableFields = computed(() =>
    (this.schema()?.fields ?? []).filter((f) => !f.isSystemField),
  )

  constructor() {
    // Reload whenever the selected entity changes.
    effect(() => {
      const id = this.entityId()
      untracked(() => void this.reload(id))
    })
  }

  async reload(entityId = this.entityId()): Promise<void> {
    this.loading.set(true)
    this.error.set(null)
    this.schema.set(null)
    this.records.set([])
    this.recordsError.set(null)
    this.creating.set(false)
    this.editingRecord.set(null)
    this.inspectingId.set(null)
    this.selectedIds.set([])
    try {
      const entityService = new Entities(this.auth.sdk)
      const entity = await entityService.getById(entityId)
      this.schema.set(entity)
      // Unlike the React sample (where the data-table widget owns the record
      // fetch), this app renders its own grid — so load the records here.
      await this.loadRecords()
    } catch (err) {
      this.error.set(
        err instanceof UiPathError ? err.message : 'Failed to load entity',
      )
    } finally {
      this.loading.set(false)
    }
  }

  /**
   * Fetches ALL records for the current entity and returns them.
   *
   * Each `getAllRecords` call returns ONE server-capped page — passing no
   * options does NOT return every row. Loop the cursor and accumulate so
   * the full record set is available to the grid and to CSV export (which
   * must not silently truncate large entities to the first page).
   */
  async loadRecords(): Promise<EntityRecord[]> {
    const schema = this.schema()
    if (!schema || entityNotSupportedReason(schema)) {
      // VDOs, InternalEntity, ChoiceSet — the records endpoint doesn't
      // apply. The UI shows a friendly notice instead.
      this.records.set([])
      return []
    }
    this.recordsLoading.set(true)
    this.recordsError.set(null)
    try {
      const entityService = new Entities(this.auth.sdk)
      const allRecords: EntityRecord[] = []
      let page = await entityService.getAllRecords(this.entityId(), {
        pageSize: 100,
      })
      allRecords.push(...page.items)
      while (page.hasNextPage && page.nextCursor) {
        page = await entityService.getAllRecords(this.entityId(), {
          cursor: page.nextCursor,
        })
        allRecords.push(...page.items)
      }
      this.records.set(allRecords)
      return allRecords
    } catch (err) {
      this.recordsError.set(
        err instanceof UiPathError ? err.message : 'Failed to load records',
      )
      return []
    } finally {
      this.recordsLoading.set(false)
    }
  }

  async exportCsv(): Promise<void> {
    const schema = this.schema()
    if (!schema) return
    this.exporting.set(true)
    try {
      // Re-fetch so the export reflects the current server state, not a
      // stale grid.
      const list = await this.loadRecords()
      if (!list.length) {
        this.toast.info('Nothing to export — table is empty')
        return
      }
      exportRecordsAsCsv(`${schema.name}.csv`, schema.fields, list)
      this.toast.success(`Exported ${list.length} records`)
    } finally {
      this.exporting.set(false)
    }
  }

  /**
   * Batch-deletes the selected rows via `Entities.deleteRecordsById`, then
   * reloads the grid. Partial failures are reported per the SDK's
   * `successRecords` / `failureRecords` split.
   */
  async deleteSelected(): Promise<void> {
    const ids = this.selectedIds()
    if (ids.length === 0) return
    this.deleting.set(true)
    try {
      const entityService = new Entities(this.auth.sdk)
      const result = await entityService.deleteRecordsById(this.entityId(), ids)
      if (result.failureRecords.length > 0) {
        this.toast.error(
          `Failed to delete ${result.failureRecords.length} of ${ids.length} records`,
          result.failureRecords[0]?.error,
        )
      } else {
        this.toast.success(
          `Deleted ${ids.length} record${ids.length === 1 ? '' : 's'}`,
        )
      }
      this.selectedIds.set([])
      await this.loadRecords()
    } catch (err) {
      this.toast.error(
        'Delete failed',
        err instanceof UiPathError ? err.message : 'Unknown error',
      )
    } finally {
      this.deleting.set(false)
    }
  }

  async onEditorSaved(action: 'created' | 'updated'): Promise<void> {
    this.creating.set(false)
    this.editingRecord.set(null)
    this.toast.success(`Record ${action}`)
    await this.loadRecords()
  }
}

// samples/data-fabric-app/src/components/EntityDetail.tsx
import { useEffect, useMemo, useState } from 'react'
import type { ColDef } from 'ag-grid-community'
import { Calendar, Download, Plus, RefreshCw } from 'lucide-react'
import { DataTable } from '@uipath/ui-widgets-datatable'
import { Button } from '@uipath/apollo-wind/components/ui/button'
import { RecordEditor } from './RecordEditor'
import { ReadOnlyRecordsTable } from './ReadOnlyRecordsTable'
import { RowInspector } from './RowInspector'
import { useAuth } from '../context/AuthContext'
import { useEntity } from '../hooks/useEntity'
import { useWidgetToolbarOverrides } from '../hooks/useWidgetToolbar'
import { exportRecordsAsCsv } from '../lib/csvExport'
import { toast } from '@uipath/apollo-wind/components/ui/sonner'
import type { EntityGetResponse } from '@uipath/uipath-typescript/entities'
import { Skeleton } from '@uipath/apollo-wind/components/ui/skeleton'
import { ChoiceSetView } from './ChoiceSetView'
import { Alert, AlertDescription, AlertTitle } from '@uipath/apollo-wind/components/ui/alert'
import { Badge } from '@uipath/apollo-wind/components/ui/badge'
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from '@uipath/apollo-wind/components/ui/tooltip'
import {
  entityNotSupportedReason,
  entityTypeTooltip,
  isReadOnlyEntity,
  isVirtualDataObject,
} from '../lib/entityTypes'

// Re-export the field-metadata helper type so any external imports keep working.
export type { EntityField } from '../hooks/useEntity'

interface Props {
  entityId: string
}

/**
 * Right-pane detail view for one entity.
 *
 * Rendering branches by entity kind:
 *  - **Regular Entity** → @uipath/ui-widgets-datatable handles the full CRUD UI
 *    (schema fetch, record fetch, inline edit, add/delete, filter, sort,
 *    pagination, foreign-key resolution, choice-set inline pickers).
 *  - **ChoiceSet** → dedicated read-only viewer via ChoiceSets service.
 *  - **VDO / InternalEntity / SystemEntity** → friendly "not viewable" notice.
 *
 * We still call `useEntity` here to pull the schema for the page header
 * (display name, description, type badge). The widget fetches schema again
 * internally — that's a small duplicate request, but the cleanest path while
 * the widget's API doesn't accept a pre-loaded schema.
 */
export function EntityDetail({ entityId }: Props) {
  const { sdk } = useAuth()
  const {
    schema,
    records,
    recordsLoading,
    recordsError,
    loading,
    error,
    reload,
    reloadRecords,
  } = useEntity(entityId)
  const [exporting, setExporting] = useState(false)

  // `creating` opens the Add data modal. `inspectingId` opens the Row
  // Inspector for that record (trigger: click the Id cell — see
  // `columnConfig['Id']`). Edits to existing rows go through the widget's
  // own inline-edit + Show Diff flow, not through this component's state.
  const [creating, setCreating] = useState(false)
  const [inspectingId, setInspectingId] = useState<string | null>(null)

  // For read-only entities (e.g. SystemEntity) the widget can't render
  // most columns — its useEntityData hook filters out system fields. We
  // render our own `<ReadOnlyRecordsTable>` instead, which means we have
  // to fetch the records ourselves (the widget would normally own that).
  useEffect(() => {
    if (schema && isReadOnlyEntity(schema)) {
      void reloadRecords()
    }
  }, [schema, reloadRecords])

  // Hide widget toolbar actions we've replaced with our own UI, and bridge
  // the widget's silent-on-success commit flow into a sonner toast so the
  // user sees confirmation when their inline edits land. See the hook for
  // details.
  useWidgetToolbarOverrides({
    readOnly: !!schema && isReadOnlyEntity(schema),
    onCommit: (kind, message) =>
      kind === 'success' ? toast.success(message) : toast.error(message),
  })

  // Per-field AG Grid column overrides — required-field asterisks, wrap +
  // autoHeight, custom Id cellRenderer that opens the Row Inspector. Must
  // live BEFORE any early returns to keep hook order stable across renders.
  const columnConfig = useMemo(() => {
    if (!schema) return undefined
    // Read-only entities (e.g. SystemEntity) get `editable: false` on every
    // column so AG Grid's inline editors never mount.
    const readOnly = isReadOnlyEntity(schema)
    const cfg: Record<string, ColDef> = {}
    // `schema.fields` can be missing when the backend returns a sparse
    // entity (e.g. some choice-set IDs return without a fields array).
    // We route choice sets to ChoiceSetDetail at App level so this loop
    // shouldn't run for them, but guard anyway to avoid a hard crash.
    for (const field of schema.fields ?? []) {
      const isRequired = field.isRequired && !field.isSystemField
      const label = field.displayName || field.name
      const colDef: ColDef = {
        wrapText: true,
        autoHeight: true,
        minWidth: 140,
        editable: !readOnly,
        // Required fields get an asterisk appended to the header. We
        // intentionally don't tint required headers/cells red — the `*`
        // alone is enough of a hint, and red highlighting got noisy on
        // entities where most columns are required.
        headerName: isRequired ? `${label} *` : label,
        headerTooltip: isRequired ? `${label} (required)` : label,
        // Keep cellStyle minimal — the widget's inline editor mounts inside
        // each cell, and any layout properties (display, flex, padding) on
        // the cell push the editor input into a second line and can prevent
        // value commits. Only style what's needed for the *display* state.
        cellStyle: {
          whiteSpace: 'normal',
          lineHeight: '1.4',
        },
        tooltipValueGetter: (params) =>
          params.value == null ? '' : String(params.value),
      }

      // Date / datetime columns: when the cell is empty, render a small
      // "Pick a date" hint with a calendar icon so the cell looks like
      // a date picker affordance instead of just being blank. Doesn't
      // affect inline-edit behaviour — AG Grid uses `cellEditor` for the
      // editing state.
      const typeName = field.fieldDataType?.name?.toUpperCase?.()
      if (
        typeName === 'DATE' ||
        typeName === 'DATETIME' ||
        typeName === 'DATETIME_WITH_TZ'
      ) {
        const isDate = typeName === 'DATE'
        const placeholderLabel = isDate ? 'Pick a date' : 'Pick a date and time'
        colDef.cellRenderer = (params: { value: unknown }) => {
          if (params.value == null || params.value === '') {
            // Match the apollo-wind `DateTimePicker` placeholder colour
            // the widget uses for empty DATETIME cells (`text-muted-foreground`)
            // so DATE and DATETIME cells look visually consistent.
            return (
              <span className="inline-flex items-center gap-1.5 text-muted-foreground">
                <Calendar className="h-3.5 w-3.5 shrink-0" />
                <span>{placeholderLabel}</span>
              </span>
            )
          }
          // Trim ISO date/time strings to the human-readable portion.
          const s = String(params.value)
          return isDate ? s.slice(0, 10) : s.slice(0, 16).replace('T', ' ')
        }
      }

      // The widget keys columnConfig by `f.displayName`. Register under
      // both displayName and name so the lookup matches in either case.
      cfg[label] = colDef
      if (field.name !== label) cfg[field.name] = colDef
    }

    // Hijack the Id column to be a clickable "inspect" link. Clicking it
    // opens RowInspector, which loads the full record via getRecordById and
    // shows ALL fields including system metadata (CreatedTime, UpdatedBy,
    // etc. — the widget filters those out of the main grid).
    cfg['Id'] = {
      headerName: 'Id',
      minWidth: 300,
      cellRenderer: (params: { value: string }) => (
        <button
          type="button"
          onClick={() => setInspectingId(params.value)}
          className="text-primary hover:underline font-mono text-xs cursor-pointer"
          title="Inspect record details"
        >
          {params.value}
        </button>
      ),
    }
    return cfg
  }, [schema])

  if (error) {
    return (
      <div className="flex-1 overflow-auto p-8">
        <Alert variant="destructive">
          <AlertTitle>Couldn't load this entity</AlertTitle>
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      </div>
    )
  }

  // While the schema loads, render a skeleton-based layout instead of a
  // full-page spinner. The user sees the page immediately, the schema usually
  // resolves in a few hundred ms, then the widget takes over with its own
  // loading state inside the table area. Avoids the jarring spinner → spinner
  // → table flicker.
  if (loading || !schema) {
    return <EntityDetailSkeleton />
  }

  const unsupportedReason = entityNotSupportedReason(schema)
  const readOnly = isReadOnlyEntity(schema)
  const showTypeBadge =
    unsupportedReason || (schema.entityType && schema.entityType !== 'Entity')
  const badgeLabel = isVirtualDataObject(schema) ? 'VDO' : schema.entityType
  const badgeTooltip = isVirtualDataObject(schema)
    ? 'Virtual Data Object — sourced from external systems via joins'
    : entityTypeTooltip(schema.entityType)

  // Editable fields for the modal form — drop system fields only. Attachment
  // (File-type) fields are kept; the RecordEditor handles them with a file
  // picker + upload/download/delete buttons.
  const editableFields = schema.fields.filter((f) => !f.isSystemField)

  return (
    <div className="flex-1 overflow-y-auto">
      <div className="p-6 flex flex-col h-full">
        {/* Page header with a Quick-add button on the right.
            The widget's own "Add Row" stays visible for bulk-style inline
            editing; this modal-based button is for single-record adds with
            up-front required-field validation. */}
        <div className="flex items-start justify-between gap-4 mb-6">
          <EntityHeader
            schema={schema}
            showTypeBadge={!!showTypeBadge}
            badgeLabel={badgeLabel}
            badgeTooltip={badgeTooltip}
            readOnly={readOnly}
          />
          {!unsupportedReason && schema.entityType !== 'ChoiceSet' && (
            <div className="flex items-center gap-2 shrink-0">
              <Button
                variant="outline"
                disabled={exporting}
                onClick={async () => {
                  // Records aren't pre-loaded with the schema (the widget
                  // owns its own data fetch). Fetch on demand here so we
                  // don't double the network cost on every page load.
                  // `reloadRecords()` returns the freshly fetched array so
                  // we don't have to wait for React's next render.
                  setExporting(true)
                  try {
                    const list = await reloadRecords()
                    if (!list.length) {
                      toast.info('Nothing to export — table is empty')
                      return
                    }
                    exportRecordsAsCsv(
                      `${schema.name}.csv`,
                      schema.fields,
                      list,
                    )
                    toast.success(`Exported ${list.length} records`)
                  } finally {
                    setExporting(false)
                  }
                }}
                title="Export records to CSV"
              >
                <Download className="h-4 w-4 mr-1.5" />
                {exporting ? 'Exporting…' : 'Export CSV'}
              </Button>
              <Button
                variant="outline"
                onClick={
                  readOnly
                    ? () => void reloadRecords()
                    : triggerWidgetRefresh
                }
              >
                <RefreshCw className="h-4 w-4 mr-1.5" />
                Refresh
              </Button>
              {/* "Add data" is hidden for read-only entities (e.g. SystemEntity)
                  — the records are queryable but not mutable. */}
              {!readOnly && (
                <Button onClick={() => setCreating(true)}>
                  <Plus className="h-4 w-4 mr-1.5" />
                  Add data
                </Button>
              )}
            </div>
          )}
        </div>

        {/* Schema (collapsible) */}
        <details className="mb-6 rounded-lg border bg-card">
          <summary className="cursor-pointer px-4 py-2 text-sm font-medium">
            Schema ({schema.fields.length} fields)
          </summary>
          <div className="border-t px-4 py-2 text-sm">
            <SchemaTable fields={schema.fields} />
          </div>
        </details>

        {/* Content varies by entity kind */}
        {schema.entityType === 'ChoiceSet' ? (
          <ChoiceSetView choiceSetId={entityId} />
        ) : unsupportedReason ? (
          <Alert>
            <AlertTitle>Records aren't viewable here</AlertTitle>
            <AlertDescription>{unsupportedReason}</AlertDescription>
          </Alert>
        ) : readOnly ? (
          // Read-only entities (e.g. SystemEntity). The data-table widget
          // filters out fields where `isSystemField: true` — for SystemEntity
          // that means every column except Id is hidden. We render our own
          // simple table that shows ALL schema fields.
          <ReadOnlyRecordsTable
            fields={schema.fields}
            records={records}
            loading={recordsLoading}
            error={recordsError}
            onInspect={(id) => setInspectingId(id)}
          />
        ) : (
          // Official UiPath widget — owns the entire records UI.
          // Docs: https://www.npmjs.com/package/@uipath/ui-widgets-datatable
          //
          // Height: the records area lives inside a flex column (the
          // wrapping `<div className="p-6 flex flex-col h-full">`), so
          // `flex-1` makes the table grow to fill whatever vertical space the
          // header + schema panel above leave behind. AG Grid needs a
          // definite height — `h-full` on the parent + `flex-1` here gives
          // it one. `min-h-[480px]` keeps it usable on short screens.
          //
          // Theme notes: the widget hard-codes ag-grid's Quartz theme; our
          // `--ag-*` overrides in src/index.css (esp. in `.dark`) flip the
          // colours to match the rest of the app's dark mode.
          <div className="rounded-lg border bg-card overflow-hidden flex-1 min-h-[480px]">
            <DataTable
              sdk={sdk}
              entityId={entityId}
              pageSize={50}
              // Show the primary key column. Other system fields
              // (CreatedTime, UpdatedTime, CreatedBy, UpdatedBy) are
              // filtered out at the widget level — see the widget's
              // useEntityData hook which does `fields.filter(f => !f.isSystemField)`.
              showIdColumn={true}
              columnConfig={columnConfig}
            />
          </div>
        )}
      </div>

      {creating && (
        <RecordEditor
          entityId={entityId}
          entityDisplayName={schema.displayName || schema.name}
          fields={editableFields}
          onClose={() => setCreating(false)}
          onSaved={async () => {
            setCreating(false)
            await reload()
          }}
        />
      )}

      {inspectingId && (
        <RowInspector
          entityId={entityId}
          recordId={inspectingId}
          schema={schema}
          onClose={() => setInspectingId(null)}
        />
      )}
    </div>
  )
}

/**
 * Programmatically clicks the widget's hidden "Refresh" button to make the
 * grid re-fetch records. We hide that button via CSS and surface our own
 * Refresh in the page header instead, so the action sits next to "Add data".
 */
function triggerWidgetRefresh() {
  const refreshBtn = Array.from(
    document.querySelectorAll<HTMLButtonElement>(
      '.uipath-datatable-container button',
    ),
  ).find((b) => b.textContent?.trim() === 'Refresh')
  refreshBtn?.click()
}

function EntityHeader({
  schema,
  showTypeBadge,
  badgeLabel,
  badgeTooltip,
  readOnly,
}: {
  schema: EntityGetResponse
  showTypeBadge: boolean
  badgeLabel: string | undefined
  badgeTooltip: string
  readOnly: boolean
}) {
  // No outer `mb-6` here — the parent layout in EntityDetail already wraps
  // this in a flex row with its own bottom margin.
  return (
    <div className="min-w-0">
      <div className="flex items-center gap-2 flex-wrap">
        <h2 className="text-2xl font-semibold truncate">
          {schema.displayName || schema.name}
        </h2>
        {showTypeBadge && badgeLabel && (
          <Tooltip>
            <TooltipTrigger asChild>
              <Badge variant="secondary">{badgeLabel}</Badge>
            </TooltipTrigger>
            <TooltipContent side="bottom" className="max-w-xs">
              {badgeTooltip}
            </TooltipContent>
          </Tooltip>
        )}
        {readOnly && (
          <Tooltip>
            <TooltipTrigger asChild>
              <Badge variant="outline">Read-only</Badge>
            </TooltipTrigger>
            <TooltipContent side="bottom" className="max-w-xs">
              This entity is managed by the platform — records can be viewed
              but not edited, added, or deleted.
            </TooltipContent>
          </Tooltip>
        )}
      </div>
      {schema.description && (
        <p className="text-sm text-muted-foreground mt-1">
          {schema.description}
        </p>
      )}
      <p className="text-xs text-muted-foreground mt-2">
        <span className="font-mono">{schema.name}</span>
        {' · '}
        {schema.fields.length} field
        {schema.fields.length === 1 ? '' : 's'}
      </p>
    </div>
  )
}

function SchemaTable({ fields }: { fields: EntityGetResponse['fields'] }) {
  return (
    <table className="w-full">
      <thead className="text-left text-xs text-muted-foreground">
        <tr>
          <th className="py-1 pr-4">Name</th>
          <th className="py-1 pr-4">Type</th>
          <th className="py-1 pr-4">Required</th>
          <th className="py-1 pr-4">System</th>
        </tr>
      </thead>
      <tbody>
        {fields.map((f) => (
          <tr key={f.id} className="border-t">
            <td className="py-1 pr-4 font-mono text-xs">{f.name}</td>
            <td className="py-1 pr-4 text-xs">
              {f.fieldDataType?.name ?? '—'}
            </td>
            <td className="py-1 pr-4 text-xs">{f.isRequired ? 'yes' : 'no'}</td>
            <td className="py-1 pr-4 text-xs">
              {f.isSystemField ? 'yes' : 'no'}
            </td>
          </tr>
        ))}
      </tbody>
    </table>
  )
}

/**
 * Skeleton placeholder rendered while the entity schema loads.
 * Same overall layout as the loaded state — title row, schema panel hint, and
 * a large rectangle where the records table will appear — so the page doesn't
 * jump when content fills in.
 */
function EntityDetailSkeleton() {
  return (
    <div className="flex-1 overflow-y-auto">
      <div className="p-6 flex flex-col h-full">
        <div className="mb-6 space-y-2">
          <Skeleton className="h-8 w-1/3" />
          <Skeleton className="h-4 w-1/2" />
          <Skeleton className="h-3 w-40" />
        </div>
        <Skeleton className="h-10 w-full mb-6" />
        <Skeleton className="flex-1 min-h-[460px] w-full" />
      </div>
    </div>
  )
}
